# Generated by Django 2.1.4 on 2019-12-03 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('book_name', models.CharField(max_length=50, unique=True, verbose_name='书名')),
                ('book_author', models.CharField(max_length=20, verbose_name='作者')),
                ('book_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='价格')),
                ('book_year', models.DateField(verbose_name='出版时间')),
                ('book_publish', models.CharField(max_length=50, verbose_name='出版社')),
                ('book_number', models.PositiveSmallIntegerField(default='5', verbose_name='总量')),
                ('book_status', models.BooleanField(default=True, verbose_name='是否可借')),
                ('book_type', models.CharField(choices=[('1', '杂志'), ('2', '书籍'), ('3', '其他')], default='2', max_length=2, verbose_name='书籍类型')),
                ('book_url_pic', models.URLField(blank=True, verbose_name='图片地址')),
                ('book_describe', models.TextField(blank=True, default='', max_length=255, verbose_name='书籍描述')),
                ('book_content', models.TextField(blank=True, default='', max_length=255, verbose_name='书籍内容')),
            ],
            options={
                'verbose_name': '图书信息表',
                'verbose_name_plural': '图书信息表',
                'db_table': 'BookInfo',
            },
        ),
        migrations.CreateModel(
            name='BorrowBookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_total', models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='借阅数')),
                ('back_time', models.DateField(auto_now_add=True, verbose_name='到馆时间')),
                ('book_remain', models.PositiveSmallIntegerField(blank=True, default='5', verbose_name='在馆数')),
                ('borrow_book_number', models.PositiveSmallIntegerField(default='5', verbose_name='总量')),
                ('borrow_book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbbi_book_id', to='user.Book', verbose_name='书籍编号')),
                ('borrow_book_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbbi_book_name', to='user.Book', to_field='book_name', verbose_name='书籍名称')),
            ],
            options={
                'verbose_name': '借阅书籍状态表',
                'verbose_name_plural': '借阅书籍状态表',
                'db_table': 'BorrowBookInfo',
            },
        ),
        migrations.CreateModel(
            name='BorrowInfo',
            fields=[
                ('borrow_info', models.DateTimeField(auto_created=True, primary_key=True, serialize=False, verbose_name='借阅记录创建时间')),
                ('browser_time', models.DateField(auto_now=True, verbose_name='借书时间')),
                ('back_time', models.DateField(auto_now=True, verbose_name='还书时间')),
                ('borrow_book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbi_book_id', to='user.Book', verbose_name='书籍编号')),
                ('borrow_book_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbi_book_name', to='user.Book', to_field='book_name', verbose_name='书籍名称')),
            ],
            options={
                'verbose_name': '借阅信息记录表',
                'verbose_name_plural': '借阅信息记录表',
                'db_table': 'BorrowInfo',
            },
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('browser_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('browser_password', models.CharField(max_length=20, verbose_name='密码')),
                ('browser_status', models.BooleanField(default=True, verbose_name='借书状态')),
                ('browser_number', models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='已借量')),
                ('browser_number_max', models.PositiveSmallIntegerField(blank=True, default='18', verbose_name='最大借书量')),
                ('overdraft', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='欠款金额')),
                ('browser_type', models.CharField(choices=[('1', '本科生'), ('2', '研究生'), ('3', '其他')], default='1', max_length=5, verbose_name='类型')),
            ],
            options={
                'verbose_name': '借阅者信息表',
                'verbose_name_plural': '借阅者信息表',
                'db_table': 'BrowserInfo',
            },
        ),
        migrations.AddField(
            model_name='borrowinfo',
            name='borrow_browser_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbi_browser_id', to='user.Browser', verbose_name='借书者编号'),
        ),
        migrations.AddField(
            model_name='borrowinfo',
            name='borrow_browser_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbi_browser_name', to='user.Browser', verbose_name='借书者姓名'),
        ),
    ]
