# Generated by Django 2.1.4 on 2019-12-03 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinfo',
            name='borrow_browser_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbi_browser_name', to='user.Browser', to_field='browser_name', verbose_name='借书者姓名'),
        ),
    ]
