# Generated by Django 2.1.4 on 2019-12-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191203_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowinfo',
            name='longtime',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='借阅天数'),
        ),
        migrations.AlterField(
            model_name='borrowinfo',
            name='back_time',
            field=models.DateField(verbose_name='还书时间'),
        ),
    ]
