# Generated by Django 2.1.4 on 2019-12-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191203_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbookinfo',
            name='hot_statistic',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='热度数'),
        ),
        migrations.AddField(
            model_name='borrowbookinfo',
            name='totals_statistics',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='被借阅总次数'),
        ),
    ]
