# Generated by Django 2.1.4 on 2019-12-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191210_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbookinfo',
            old_name='hot_statistic',
            new_name='hot_statistics',
        ),
    ]
